#!/usr/bin/env python3
"""Embed the web app's files in the firmware, gzipped, as a C table web_server serves from.

    embed_assets.py OUT.c URLPATH=FILE [URLPATH=FILE ...]

Each FILE is gzipped (mtime 0, so the same files always give the same image) and written as a
byte array, with its URL path and Content-Type, into OUT.c's `webui_assets` table. A file that
gzip does not shrink is stored as it is. The build runs this whenever a file changes.

Standard library only.
"""

from __future__ import annotations

import gzip
import sys
from pathlib import Path

TYPES = {
    ".html": "text/html; charset=utf-8",
    ".css": "text/css; charset=utf-8",
    ".js": "text/javascript; charset=utf-8",
    ".json": "application/json",
    ".svg": "image/svg+xml",
    ".png": "image/png",
    ".ico": "image/x-icon",
}


def c_bytes(data: bytes) -> str:
    rows = []
    for i in range(0, len(data), 20):
        rows.append("    " + ", ".join(f"0x{b:02x}" for b in data[i : i + 20]) + ",")
    return "\n".join(rows)


def main() -> int:
    if len(sys.argv) < 3:
        print(__doc__, file=sys.stderr)
        return 2
    out = Path(sys.argv[1])
    arrays, rows = [], []
    total_raw = total_stored = 0
    for n, spec in enumerate(sys.argv[2:]):
        path, _, src = spec.partition("=")
        if not path.startswith("/") or not src:
            sys.exit(f"error: expected /url/path=file, got {spec!r}")
        raw = Path(src).read_bytes()
        kind = TYPES.get(Path(src).suffix.lower())
        if kind is None:
            sys.exit(f"error: no Content-Type for {src}")
        packed = gzip.compress(raw, compresslevel=9, mtime=0)
        gz = len(packed) < len(raw)
        data = packed if gz else raw
        total_raw += len(raw)
        total_stored += len(data)
        arrays.append(f"/* {path} ({len(raw)} bytes{', gzipped' if gz else ''}) */\n"
                      f"static const uint8_t a{n}[] = {{\n{c_bytes(data)}\n}};\n")
        rows.append(f'    {{ "{path}", "{kind}", a{n}, sizeof(a{n}), {"true" if gz else "false"} }},')
    text = (
        "/* Generated by components/webui/embed_assets.py: do not edit. */\n"
        "#include <stdint.h>\n#include \"web_server.h\"\n\n"
        + "\n".join(arrays)
        + "\nconst web_asset_t webui_assets[] = {\n" + "\n".join(rows) + "\n};\n"
        + f"const size_t webui_asset_count = {len(rows)};\n"
    )
    if not out.exists() or out.read_text() != text:
        out.write_text(text)
    print(f"webui: {len(rows)} files, {total_raw} bytes, {total_stored} embedded")
    return 0


if __name__ == "__main__":
    sys.exit(main())
